### ISSUE TITLE
Not Working (from web interface)

### ISSUE THREAD

**Issue by edo9k** [epsil/spotify-js#5]
I was looking for a way to create mixed Spotify playlists and found this project, which can even be used from the terminal (the most convenient way). 

But it ain't working, why? PLZ HALP

**Comment by epsil** [comment]
**Short answer:** Use the terminal version, the web version is currently broken.

**Long answer:** Spotify recently changed their [authorization requirements](https://developer.spotify.com/web-api/authorization-guide/). One now has to authorize with their server before doing any requests, and the requests have to be supplied with a token that one obtains from the authorization.

There are several authorization flows. The terminal version uses the [client credentials flow](https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow), which is transparent as far as the user is concerned. However, that flow cannot be used by the web version, because Spotify's authorization server rejects cross site requests.

Thus, the web version has to be rewritten to use one of the other authorization flows, which require the user to log in with their Spotify account before the playlist is generated. Potentially, this could provide a better interface for creating playlists than the current "copy and paste" scheme. However, it requires a substantial refactoring of the web version's code, which is currently just a few lines of jQuery invoking the generator.

**Comment by edo9k** [comment]
Thanks a lot man! Great tool!
